### ISSUE TITLE
Same values every time run or compiled

### ISSUE THREAD

**Issue by gcsprojects** [davepl/blackjack#2]
Not sure what's going on, but whenever the code is compiled and run, I always get the same output

```
Player hand value: 18
Dealer hand value: 16
```

I'll admit I'm new to C++ and still learning, but nothing obvious standing out to suggest why those two values would always be returned after each compile and/or run of the resulting app

**Comment by davepl** [comment]
That’s by design, but easily fixed.

The random number generator always starts with the same number, and works from there.  And it starts the same each time.  So each time you run the program, you get the same “random” numbers.  

You can “randomize” it by calling a function called srand() with some value, but what do you pick that’s random to get it started?

If you have a millisecond timer on your system, you can do something like:

srand(mills())

…and that should get you random card numbers.  You only need to do it once when your program is starting, in main.

Hope this helps!

- Dave

#include <ctime>
#include <cstdlib>

int main() {
    srand(static_cast<unsigned int>(time(0)));

    // Your code here

    return 0;
}

..or if you’re feeling fancy:

#include <random>

int main() {
    std::random_device rd;
    std::mt19937 mt(rd());
    std::uniform_int_distribution<int> dist(1, 10);

    int random_number = dist(mt);

    // Your code here, after updating the game to use the dist() object

    return 0;
}

**Comment by gcsprojects** [comment]
Thank you kind sir!
I shall have a play around and see if I can get it working
